name: Code Formant and Testing
description: Iniciate code formant and unit tests

runs:
  using: 'composite'
  steps:
    - name: Lint code
      run: npm run lint

    - name: Run unit tests
      run: npm run test
