name: Deploy Vercel

on:
  workflow_call:
    inputs:
      vercel-token:
        description: Vercel token
        required: true
        type: string
      mode:
        description: Deploy mode
        required: true
        type: string
        default: 'production'

jobs:
  deploy-vercel:
    environment:
      name: 'Staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: PROD Vercel Deployment
        if: ${{ inputs.mode == 'production' }}
        run: |
          vercel pull --yes --environment=production --token=${{ inputs.vercel-token }}
          vercel build --prod --token=${{ inputs.vercel-token }}
          vercel deploy --prebuilt --prod --token=${{ inputs.vercel-token }}

      - name: PREVIEW Vercel Deployment
        if: ${{ inputs.mode == 'preview' }}
        run: |
          vercel pull --yes --environment=preview --token=${{ inputs.vercel-token }}
          vercel build --token=${{ inputs.vercel-token }}
          DEPLOY_URL=$(vercel deploy --token=${{ inputs.vercel-token }})
          echo "DEPLOY_URL=${DEPLOY_URL}" >> $GITHUB_ENV

      - name: Comment with preview URL
        if: ${{ inputs.mode == 'preview' }}
        uses: actions/github-script@v7
        with:
          script: |
            const {DEPLOY_URL} = process.env
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview URL: ${DEPLOY_URL}`,
            })
