name: Deploy on push

on:
  push:
    branches:
      - master

jobs:
  deploy-netlify:
    uses: ./.github/actions/deploy-netlify
    secrets: inherit

  deploy-vercel:
    needs: deploy-netlify
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
